### ISSUE TITLE
目前無法使用

### ISSUE THREAD

**Issue by dse12345z** [DaidoujiChen/DaiYoutubeParser#3]
tag.src = "http://www.youtube.com/player_api";
更換底下
tag.src = "https://www.youtube.com/iframe_api";

The code sample in the Getting started section has been updated to reflect that the URL for the IFrame Player API code has changed to http://www.youtube.com/iframe_api. To ensure that this change does not affect existing implementations, the old URL (http://www.youtube.com/player_api) will continue to work.

需要將 player_api 更換成 iframe_api, 並使用 https.
官方：https://developers.google.com/youtube/iframe_api_reference#Getting_Started

**Comment by MiaShopgal** [comment]
所以官方騙人？ＸＤＤＤ 
it's not working now XD

不對＝＝ 
July 19, 2012 講的.. XD

**Comment by DaidoujiChen** [comment]
解馬叔叔嗎

**Comment by DaidoujiChen** [comment]
Hello @dse12345z , @MiaShopgal 

這件事情其實以前也有發生過
就是 webview 開起來看的話
會發現已經 load 到那一個頁
但是不會自動開始播放
過幾天之後他就自己好了
也不懂為什麼

**Comment by dse12345z** [comment]
哦哦 原來如此, 感謝 !!

**Comment by dse12345z** [comment]
巷弄 XD

**Comment by DaidoujiChen** [comment]
你可以跟 @jeff1229 預告馬叔叔也是這個問題了
哈哈

**Comment by dse12345z** [comment]
好唷! , OωO

**Comment by DaidoujiChen** [comment]
@dse12345z 

你改完有可以 work 嗎?
我怎麼改下去好像還是不行?

update...星巴克網路太慢

**Comment by dse12345z** [comment]
可以了 ?

**Comment by DaidoujiChen** [comment]
對阿, 就改你上次說的那個網址就可以

**Comment by MiaShopgal** [comment]
看來它不會自我修復了...

**Comment by dse12345z** [comment]
QAQ

**Comment by DaidoujiChen** [comment]
XD
